name: Sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'

env:
  IC_SOURCE_REPO_URL: https://github.com/nginxinc/kubernetes-ingress.git
  IC_SOURCE_BRANCH: master
  IC_DEST_BRANCH: master

jobs:
  repo-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: repo-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ env.IC_SOURCE_REPO_URL }}
          source_branch: ${{ env.IC_SOURCE_BRANCH }}
          destination_repo: ${{ secrets.SYNC_DEST_REPO_URL }}
          destination_branch: ${{ env.IC_DEST_BRANCH }}
          ssh_private_key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
